# https://rust-lang.github.io/rustfmt/?version=v1.8.0
# comment_width = 120
edition = "2021"
# format_code_in_doc_comments = true
# format_strings = true
# group_imports = "StdExternalCrate"
hard_tabs = false
# imports_granularity = "Crate"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
style_edition = "2021"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
# wrap_comments = true
