# [Valid options] off / error / warn / info / debug / trace
log_level = "info"
# The port to run the server on
port = 9000
# The absolute system path to the directory that will be the file browser root directory
root_dir = "/my/files"
