export enum FileType {
  ARCHIVE = 'archive',
  AUDIO = 'audio',
  COMPRESSED = 'compressed',
  DATABASE = 'database',
  DIAGRAM = 'diagram',
  DOCUMENT = 'document',
  EBOOK = 'ebook',
  EXECUTABLE = 'executable',
  FILE = 'file',
  FONT = 'font',
  FORMULA = 'formula',
  GEOSPATIAL = 'geospatial',
  IMAGE = 'image',
  METADATA = 'metadata',
  MODEL = 'model',
  PACKAGE = 'package',
  PLAYLIST = 'playlist',
  PRESENTATION = 'presentation',
  ROM = 'rom',
  SPREADSHEET = 'spreadsheet',
  SUBTITLE = 'subtitle',
  TEXT = 'text',
  UNKNOWN = 'unknown',
  VDISK = 'vdisk',
  VIDEO = 'video',
};
